# Workflow Name
name: Compile Updated Website

# Control when the action will run:
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Controls what to do:
jobs:
  compile: # Used as the job name if the workflow wasn't named.
    # Stop if the commit message that triggered this workflow contains the words "skip ci".
    if: "!contains(github.event.commits[0].message, 'skip ci')"
    runs-on: ubuntu-latest
    
    steps:
      # Using the commit that triggered this workflow copy all files to a safe space.
      - uses: actions/checkout@v2
      - name: Compiling website
        run: |
          cp -rf . ../website
      
     